In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
csv_data = pd.read_csv('diabetes.csv')

In [3]:
csv_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [4]:
csv_data.isnull().count()

Pregnancies                 768
Glucose                     768
BloodPressure               768
SkinThickness               768
Insulin                     768
BMI                         768
DiabetesPedigreeFunction    768
Age                         768
Outcome                     768
dtype: int64

In [5]:
data = csv_data[['Glucose', 'Insulin', 'BMI', 'Age', 'DiabetesPedigreeFunction', 'Outcome']]

In [6]:
data.head()

Glucose  Insulin   BMI  Age  DiabetesPedigreeFunction  Outcome
0      148        0  33.6   50                     0.627        1
1       85        0  26.6   31                     0.351        0
2      183        0  23.3   32                     0.672        1
3       89       94  28.1   21                     0.167        0
4      137      168  43.1   33                     2.288        1

In [7]:
x = data[['Glucose', 'Insulin', 'BMI', 'Age', 'DiabetesPedigreeFunction']]

In [8]:
y = data[['Outcome']]

In [9]:
y = np.ravel(y)

In [63]:
##############################################################################################
##############################################################################################
##############################################################################################
##############################################################################################
#                  Pima Indians Diabetes Database using Logistic Regression                  #
##############################################################################################
##############################################################################################
##############################################################################################
##############################################################################################

In [11]:
# train test data splitting
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [12]:
X_train, X_test, y_train, y_test = train_test_split(x, y, train_size=0.8)

In [13]:
X_train.shape

(614, 5)

In [14]:
X_test.shape

(154, 5)

In [15]:
y_train.shape

(614,)

In [16]:
y_test.shape

(154,)

In [17]:
# importing model
from sklearn.linear_model import LogisticRegression

In [18]:
# Model
model = LogisticRegression()

In [19]:
model.fit(X_train, y_train)

LogisticRegression()

In [20]:
y_predicted = model.predict(X_test)

In [21]:
y_predicted

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [22]:
y_test

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [23]:
accuracy = accuracy_score(y_test, y_predicted)*100

In [24]:
accuracy

77.92207792207793

In [64]:
##############################################################################################
##############################################################################################
##############################################################################################
##############################################################################################
#                  Pima Indians Diabetes Database using Decision Trees                       #
##############################################################################################
##############################################################################################
##############################################################################################
##############################################################################################

In [26]:
# model importing
from sklearn.tree import DecisionTreeClassifier as de

In [27]:
model_de = de()

In [28]:
model_de.fit(X_train, y_train)

DecisionTreeClassifier()

In [29]:
y_predicted_de = model_de.predict(X_test)
y_predicted_de

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0],
      dtype=int64)

In [30]:
accuracy_de = accuracy_score(y_test, y_predicted_de)*100

In [31]:
accuracy_de

68.83116883116884

In [65]:
##############################################################################################
##############################################################################################
##############################################################################################
##############################################################################################
#                  Pima Indians Diabetes Database using Random Forest                        #
##############################################################################################
##############################################################################################
##############################################################################################
##############################################################################################

In [33]:
# importing model
from sklearn.ensemble import RandomForestClassifier as rf

In [34]:
model_rf = rf()

In [35]:
model_rf.fit(X_train, y_train)

RandomForestClassifier()

In [37]:
y_predicted_rf = model_rf.predict(X_test)

In [38]:
y_predicted_rf

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [50]:
accuracy_rf = accuracy_score(y_test, y_predicted_rf)*100

In [51]:
accuracy_rf

80.51948051948052

In [62]:
##############################################################################################
##############################################################################################
##############################################################################################
##############################################################################################
#           Pima Indians Diabetes Database using Support Vector Machines (SVM)               #
##############################################################################################
##############################################################################################
##############################################################################################
##############################################################################################

In [43]:
# import model
from sklearn import svm

In [45]:
model_svm = svm.SVC()

In [46]:
model_svm.fit(X_train, y_train)

SVC()

In [48]:
y_predicted_svm = model_svm.predict(X_test)
y_predicted_svm

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [49]:
accuracy_svm = accuracy_score(y_test, y_predicted_svm)*100
accuracy_svm

78.57142857142857